name: Build and Email Flutter App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.x
        
    - name: Flutter Upgrade
      run: flutter upgrade

    - name: Build APK
      run: flutter build apk --release
      
    - name: Check files
      run: ls
      
    - name: Send Email
    - name: Authenticate with Google Drive
      uses: rishabhp/setup-gdrive@v3
      with:
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Upload to Google Drive
      run: gdrive upload -p <PARENT_FOLDER_ID> build/app/outputs/apk/release/app-release.apk

    - name: Send email
      uses: actions/email@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username:  ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: my-helath mobile application is released.
        body: |
          Hello,
          Your Flutter app's APK is ready for download.
          Please use the following link to download it:APK for android users is also attached with this email. 
          Thank you.
        attachments: ./build/app/outputs/apk/debug/app-debug.apk
        to: ${{ secrets.SEND_GMAIL_ADDRESS }}
        from: ${{ secrets.GMAIL_ADDRESS }}
