name: Build and Email Flutter App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.x
        
    - name: Flutter Upgrade
      run: flutter upgrade

    - name: Build APK
      run: flutter build apk --release
      
    - name: Check files
      run: ls

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username:  ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: my-helath mobile application is released.
        body: apk is uploaded to following link!!!! Thank you.
        attachments: ./build/app/outputs/apk/debug/app-debug.apk
        to: pasanransika1@gmail.com
        from: ${{ secrets.GMAIL_ADDRESS }}
