name: Build and Email Flutter App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.x
        
    - name: Flutter Upgrade
      run: flutter upgrade

    - name: Build APK
      run:  flutter build apk --debug
      
    - name: Install zip unzip
      run: sudo apt install zip unzip tree
      
    - name: Compress APK
      run: zip -r debug.zip ./build/app/outputs/apk/debug
      
    - name: File tree view
      run: tree

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username:  ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: my-helath mobile application is released.
        body: |
          Hello,
          Your Flutter app's APK is ready for download.
          APK for android users is also attached with this email.
          Thank you.
        attachments: debug.zip
        to: ${{ secrets.SEND_GMAIL_ADDRESS }}
        from: ${{ secrets.GMAIL_ADDRESS }}
