name: Build and Email Flutter App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.x
        
    - name: Flutter Upgrade
      run: flutter upgrade

    - name: Build APK
      run:  flutter build apk --release
      
#     - name: Install zip unzip
#       run: sudo apt install zip unzip tree
      
#     - name: Compress APK
#       run: zip -r debug.zip ./build/app/outputs/apk/debug
      
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path:  build/app/outputs/apk/release/app-release.apk
        
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username:  ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: my-helath mobile application is released.
        body: |
          Hello,
          
          Your Flutter app's APK is ready for download.
          From following link you can download the latest APK for the Flutter app.
          
          Download link - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          Thank you
        attachments: commits.txt
        to: ${{ secrets.SEND_GMAIL_ADDRESS }}
        from: ${{ secrets.GMAIL_ADDRESS }}
        cc: ${{ secrets.GMAIL_ADDRESS_JASON }}
