name: Build and Email Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.x

    - name: Build APK
      run: flutter build apk --release

    - name: Email APK
      uses: sarah/email-action@v1
      env:
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      with:
        to: example@gmail.com
        subject: "New Flutter App APK"
        body: "Attached is the latest APK for the Flutter app."
        attachments: app/build/app/outputs/apk/release/app-release.apk
