name: Build and Email Flutter App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 1.22.x
        
    - name: Flutter Upgrade
      run: flutter upgrade

    - name: Build APK
      run: flutter build apk --release

    - name: Email APK
      run: |
          echo "Sending email with the APK file..."
          curl --url "smtp://smtp.gmail.com:587"  --mail-from ${{ secrets.GMAIL_USERNAME }} --mail-rcpt pasanransika1@gmail.com   --upload-file build/app/outputs/apk/release/app-release.apk   --user ${{ secrets.GMAIL_USERNAME }}:${{ secrets.GMAIL_PASSWORD }} --insecure -v --mail-auth ${{ secrets.GMAIL_USERNAME }}
     
